version: "3"
services:
  sql:
    build: ./sql
    volumes:
      - express-misquote:/var/lib/mysql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: ./frontend
    depends_on:
      - node
    ports:
      - 80:80
  node:
    build: ./backend
    env_file:
      - .env
    ports:
      - 8080:4200
    user: "node"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/utils:/home/node/app/utils/
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
volumes:
  express-misquote: